const express = require ("express")
const router = express.Router()
const controller = require('../controllers/ListingController')

router.get('/listings', controller.GetAllListings)
router.post('/listings/post', controller.PostListing)
router.delete('/listings/deleteListing', controller.DeleteListing)
router.delete('/listings/deleteAddress', controller.DeleteAddress)
router.delete('/listings/deleteAddressAndListing', controller.DeleteAddressAndListing)
router.post('/listings/postPhoto', controller.PostPhoto)
router.get('/listings/getPhotos', controller.GetPhoto)
router.delete('/listings/deletePhotos', controller.DeletePhoto)
router.get('/listings/getListingPriceMore', controller.GetListingPriceMore)
router.get('/listings/getListingPriceLess', controller.GetListingPriceLess)
router.get('/listings/getListingBedsMore', controller.GetListingBedsMore)
router.get('/listings/getListingBedsLess', controller.GetListingBedsLess)
router.get('/listings/getListingBathsMore', controller.GetListingBathsMore)
router.get('/listings/getListingBathsLess', controller.GetListingBathsLess)
router.get('/listings/getListingCity', controller.GetListingCity)
router.get('/listings/getListingZipcode', controller.GetListingZipcode)
router.get('/listings/getListingState', controller.GetListingState)
router.put('/listings/updateAddress', controller.UpdateAddress)

module.exports = router;